before_install:
  - gem update fastlane
  - fastlane --version
  - gem cleanup
  - brew update
  - brew outdated xctool || brew upgrade xctool
language: objective-c
osx_image: xcode7.2
script:
  - fastlane travis
