before_install:
  - sudo systemsetup -settimezone Europe/Tallinn
  - echo -e "machine bitbucket.org\n  login fassko\n  password $CI_USER_PASSWORD" >> ~/.netrc
  - gem update fastlane --no-document
  - fastlane --version
  - gem update xcodeproj --no-document
  - gem install cocoapods
  - gem cleanup
  - pod cache clean --all
  - pod install --repo-update
language: objective-c
osx_image: xcode9.4
script:
  - fastlane travis
env:
  - FASTLANE_XCODE_LIST_TIMEOUT=120
notifications:
  email: false
