before_install:
  - echo -e "machine bitbucket.org\n  login fassko\n  password $CI_USER_PASSWORD" >> ~/.netrc
  - gem update fastlane --no-document
  - gem install cocoapods
  - pod repo update
  - gem cleanup
  - fastlane --version
  - pod --version
language: objective-c
osx_image: xcode8
script:
  - fastlane travis --verbose