before_install:
  - gem update cocoapods --no-document --pre
  - gem update fastlane --no-document
  - fastlane --version
  - gem cleanup
  - brew outdated xctool || brew upgrade xctool
  - pod --version
  - pod repo update --silent
language: objective-c
osx_image: xcode8
script:
  - fastlane travis
notifications: change