# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      
      - run:
          name: Before Install
          command: echo -e "machine bitbucket.org\n  login fassko\n  password $CI_USER_PASSWORD" >> ~/.netrc  
          
      - run:
          name: Install
          command: |
            gem install fastlane --no-doc
            gem cleanup

      # Install CocoaPods
      - run:
          name: Update CocoaPods
          command: |
            pod repo update --silent
            pod cache clean --all
            pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane circleci
